#+title: Proyecto 1: FIUNAMFS

#+BEGIN_SRC yaml
Elaborado por Gerardo Torres Mayén
#+END_SRC

** Descripción del proyecto

Sistema de archivos con lenguaje C y OpenMP.
OpenMP es una API para programación concurrente y la documentación relacionada con los compiladores compatibles con openMP están en el siguiente enlace:

#+BEGIN_SRC yaml

https://www.openmp.org/resources/openmp-compilers-tools/

#+END_SRC
Yo utilicé el compilador GCC versión 6.3.0 y adicionalmente instalé el package 'mingw32-libpthreadgc', tengo entendido que sólo es para multithreading en Windows.
Para compilar con GCC un archivo C que contiene directivas o funciones de openMP se usa el siguiente comando:

#+BEGIN_SRC yaml

gcc archivo.c -fopenmp -o ejecutable.exe

#+END_SRC

Para que el programa inicie hay que probar el siguiente comando:

#+BEGIN_SRC yaml

ejecutable.exe fiunamfs.img

#+END_SRC

Debido al requisito de almacenar los enteros en little endian, cada que se lee o se escribe un entero en el pseudodispositivo se hace una conversión de big endian a Little endian. Ya que si el sistema donde trabajamos es big endian, así se guardarán los enteros en el sistema.

El respaldo bibliográfico del proyecto es el siguiente:

#+BEGIN_SRC yaml

[](https://developer.ibm.com/articles/au-endianc/)

#+END_SRC