FROM python:3.9-alpine AS base
WORKDIR /app
COPY requirements.txt .
FROM base AS dependencies
RUN pip install --no-cache-dir --user -r requirements.txt
FROM base AS source
COPY . .
FROM dependencies AS prod
COPY --from=source /app .
CMD ["python", "super_main.py"]