# -*- coding: utf-8 -*-
"""ProgramaP03SO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nZCf8_-RS5s27SeeDQ8BJRQpTEBu5XV7
"""

#Programa P03 Sistemas Operativos
name = input("Ingresa tu nombre: ")

print("Hola mundo, bienvenido ", name)